### ISSUE TITLE
Tasks: Requirement, Defects is not synchronized to Eclipse completely

### ISSUE THREAD

**Issue by nhcuong** [janotav/ali-idea-plugin#47]
Test with ALM 12.50
Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
HP ALI Dev For Eclipse: 3.8.1.20150804-2304-RELEASE
![eclipse_sync_task](https://cloud.githubusercontent.com/assets/15120553/10505043/d2da2de8-7332-11e5-99b1-12fa5b434f7f.jpg)

**Comment by janotav** [comment]
This plugin has no relation to Eclipse, you need to report your defect elsewhere.
