### ISSUE TITLE
User cannot delete attachement in Eclipse

### ISSUE THREAD

**Issue by nhcuong** [janotav/ali-idea-plugin#48]
Test with ALM 12.50
Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
HP ALI Dev For Eclipse: 3.8.1.20150804-2304-RELEASE
![delete_attachment](https://cloud.githubusercontent.com/assets/15120553/10505181/b6f05a74-7334-11e5-8fa1-38eeb721a7d1.jpg)

**Comment by janotav** [comment]
This plugin has no relation to Eclipse, you need to report your defect elsewhere.
