### ISSUE TITLE
Fail to Submit after attach file for Requirement

### ISSUE THREAD

**Issue by nhcuong** [janotav/ali-idea-plugin#49]
Test with ALM 12.50
Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
HP ALI Dev For Eclipse: 3.8.1.20150804-2304-RELEASE
![attachment_requirement](https://cloud.githubusercontent.com/assets/15120553/10505663/fbcdfd18-7339-11e5-8e3e-294c72a3b445.jpg)

**Comment by janotav** [comment]
This plugin has no relation to Eclipse, you need to report your defect elsewhere.
