### ISSUE TITLE
User cannot set properties for some fields of defect

### ISSUE THREAD

**Issue by nhcuong** [janotav/ali-idea-plugin#50]
Test with ALM 12.50
Eclipse Java EE IDE for Web Developers.
Version: Mars.1 Release (4.5.1)
HP ALI Dev For Eclipse: 3.8.1.20150804-2304-RELEASE
![defect_attributes](https://cloud.githubusercontent.com/assets/15120553/10505887/33a49358-733c-11e5-9d6b-3fd7ead814ec.jpg)

**Comment by janotav** [comment]
This plugin has no relation to Eclipse, you need to report your defect elsewhere.
