### ISSUE TITLE
Old comments have been removed when add new one.

### ISSUE THREAD

**Issue by nhcuong105** [janotav/ali-idea-plugin#51]
Test with HP ALI 3.15.141.177.4, IntelliJ 15.0.2, AGM buildtime=ALI-20151220-2358
buildversion=2.50-nightly-4260-SNAPSHOT
------------------------------------------------------
See pic for more details.
![idea_comment](https://cloud.githubusercontent.com/assets/5266717/11989596/1f8c3c12-aa33-11e5-8ab0-c028952c593f.jpg)

**Comment by janotav** [comment]
Fixed
